# Generated by Django 5.2.17 on 2026-09-08 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Temporary seat reservation expires at this time.', null=True),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['show', 'status', 'expires_at'], name='payment_show_status_exp'),
        ),
    ]
