# Generated by Django 5.2.17 on 2026-09-08 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_paymenttransaction_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('pending', 'Refund Pending'), ('completed', 'Refund Completed'), ('failed', 'Refund Failed')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='booking_booked_at_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'booked_at'], name='booking_show_booked_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booked_at'], name='booking_user_booked_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['show', 'created_at'], name='payment_show_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['refund_status', 'refunded_at'], name='payment_refund_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'created_at'], name='review_movie_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['created_at'], name='review_report_created_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['show_date', 'show_time'], name='show_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['theater', 'show_date'], name='show_theater_date_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'show_date'], name='show_movie_date_idx'),
        ),
    ]
